ARG FAMILY=ubuntu
ARG VERSION=jammy
FROM $FAMILY:$VERSION as builder
ARG DEBIAN_FRONTEND=noninteractive

RUN mkdir /usr/depot
WORKDIR /usr/depot

RUN apt-get update \
    &&  apt-get -y install make curl jq tmux unzip \
    &&	apt-get clean \
    &&	rm -rf /bd_build \
    &&	rm -rf /tmp/* /var/tmp/* \
    &&	rm -rf /var/lib/apt/lists/* \
    &&	rm -f /etc/ssh/ssh_host_*

COPY ubuntu_installs/* .
